name: 构建 Armbian

on:
  workflow_dispatch:
    inputs:
      board:
        description: '开发板型号'
        type: choice
        default: hinlink-h68k
        options: &boardOpts
          - hinlink-h28k
          - hinlink-h66k
          - hinlink-h68k
          - hinlink-h88k
          - hinlink-hnas
          - hinlink-ht2
      branch:
        description: '选择Armbian 分支'
        type: choice
        default: current
        options: &branchOpts
          - current
          - edge
      release:
        description: '选择发行版'
        type: choice
        default: trixie
        options: &relOpts
          - bookworm
          - bullseye
          - buster
          - focal
          - jammy
          - noble
          - oracular
          - plucky
          - sid
          - trixie
      build_desktop:
        description: '是否需要构建桌面版？'
        type: choice
        default: 'no'
        options: &boolOpts
          - 'yes'
          - 'no'
      build_minimal:
        description: '是否需要构建最小化系统？'
        type: choice
        default: 'no'
        options: &boolOpts
          - 'yes'
          - 'no'
      kernel_configure:
        description: '是否需要配置内核？'
        type: choice
        default: 'no'
        options: *boolOpts

jobs:
  build:
    runs-on: ubuntu-22.04
    name: ${{ inputs.board }} · ${{ inputs.branch }} · ${{ inputs.release }}

    steps:
      - name: 签出当前仓库代码
        uses: actions/checkout@v4

      - name: 安装系统依赖
        run: |
          sudo apt-get update -qq
          xargs -a <(curl -fsSL https://is.gd/depend_ubuntu2204_armbian) \
            sudo apt-get install -y --no-install-recommends
          sudo apt-get clean
          sudo systemctl start docker

      - name: 先克隆编译仓库
        run: |
          git clone --depth=1 --branch=main https://github.com/armbian/build.git build
          
      - name: 生成环境变量
        run: |
          {
            echo "BOARD=${{ inputs.board }}"
            echo "BRANCH=${{ inputs.branch }}"
            echo "RELEASE=${{ inputs.release }}"
            echo "BUILD_DESKTOP=${{ inputs.build_desktop }}"
            echo "BUILD_MINIMAL=${{ inputs.build_minimal }}"
            echo "KERNEL_CONFIGURE=${{ inputs.kernel_configure }}"
          } >> "$GITHUB_ENV"

      - name: 编译
        working-directory: build
        run: |
          ./compile.sh build \
            BOARD="${BOARD}" \
            BRANCH="${BRANCH}" \
            RELEASE="${RELEASE}" \
            BUILD_DESKTOP="${BUILD_DESKTOP}" \
            BUILD_MINIMAL="${BUILD_MINIMAL}" \
            KERNEL_CONFIGURE="${KERNEL_CONFIGURE}"
            
      - name: 本地极限压缩
        working-directory: build/output
        run: |
          # 安装 pixz（多线程 xz）或回退 xz
          sudo apt-get update -qq && sudo apt-get install -y pixz || true
          
          # 打包 + 极限压缩
          if command -v pixz >/dev/null; then
            tar -I 'pixz -9' -cf images.tar.xz images/
          else
            tar -cJf images.tar.xz images/
          fi
          
          # 校验大小
          ls -lh images.tar.xz
          
      - name: 上传单文件
        uses: actions/upload-artifact@v4
        with:
          name: armbian-${{ env.BOARD }}-${{ env.RELEASE }}-images.tar.xz
          path: build/output/images.tar.xz
          retention-days: 7

      - name: 清理
        if: always()
        run: |
          sudo rm -rf build/output/debs build/cache/root build/cache/sources
