name: Build Armbian

on:
  workflow_dispatch:
    inputs:
      board:
        type: choice
        description: '开发板型号 (hinlink-h68k)'
        options:
          - hinlink-h28k
          - hinlink-h66k
          - hinlink-h68k
          - hinlink-h88k
          - hinlink-hnas
          - hinlink-ht2
        required: true
        default: 'hinlink-h68k'
      branch:
        type: choice
        description: 'Armbian 分支 (如: current, edge)'
        options:
          - current
          - edge
        required: true
        default: 'current'
      release:
        type: choice
        description: '发行版 (如: bookworm, bullseye, buster, focal, jammy, noble, oracular, plucky, sid, trixie)'
        options:
          - bookworm
          - bullseye
          - buster
          - focal
          - jammy
          - noble
          - oracular
          - plucky
          - sid
          - trixie
        required: true
        default: 'trixie'
      build_desktop:
        type: choice
        description: '是否构建桌面版 (yes/no)'
        options:
          - 'yes'
          - 'no'
        required: true
        default: 'no'
      build_minimal:
        type: choice
        description: '是否构建最小化系统 (yes/no)'
        options:
          - 'yes'
          - 'no'
        required: true
        default: 'yes'
      kernel_configure:
        type: choice
        description: '是否配置内核 (yes/no)'
        options:
          - 'yes'
          - 'no'
        required: true
        default: 'no'

env:
  BUILD_ARGS: ""

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
       
#    - name: 安装依赖
#      run: |
#        sudo apt update -y
#        sudo apt full-upgrade -y
#        sudo apt install $(curl -fsSL https://is.gd/depend_ubuntu2204_armbian)
#        sudo apt autoremove --purge
#        sudo apt clean

    - name: 安装最新 Docker（可选）
      run: |
        set -e
        # 1. 卸载 runner 自带的旧包（可选）
        sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
        # 2. 装官方仓库
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl gnupg lsb-release
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
        sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo \
          "deb [arch=$(dpkg --print-architecture) \
          signed-by=/etc/apt/keyrings/docker.gpg] \
          https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

        # 3. 安装 engine + cli + buildx + compose v2
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

        # 4. 启动并加入组（runner 默认已在 docker 组，可省）
        sudo systemctl enable --now docker
        docker version
        docker buildx version
        docker compose version
    
    - name: 克隆 Armbian 构建系统
      run: |
        git clone --single-branch --depth=1 --branch=main https://github.com/armbian/build.git build
        
    - name: 设置构建参数
      run: |
        cd build
        # 设置构建参数，使用正确的默认值
        echo "BOARD=${{ github.event.inputs.board || 'hinlink-h68k' }}" >> $GITHUB_ENV
        echo "BRANCH=${{ github.event.inputs.branch || 'current' }}" >> $GITHUB_ENV
        echo "RELEASE=${{ github.event.inputs.release || 'trixie' }}" >> $GITHUB_ENV
        echo "BUILD_DESKTOP=${{ github.event.inputs.build_desktop || 'no' }}" >> $GITHUB_ENV
        echo "BUILD_MINIMAL=${{ github.event.inputs.build_minimal || 'yes' }}" >> $GITHUB_ENV
        echo "KERNEL_CONFIGURE=${{ github.event.inputs.kernel_configure || 'no' }}" >> $GITHUB_ENV
        
    - name: 编译 Armbian
      run: |
        cd build
        # 开始编译，使用新的命令格式
        ./compile.sh build \
          BOARD=${{ env.BOARD }} \
          BRANCH=${{ env.BRANCH }} \
          RELEASE=${{ env.RELEASE }} \
          BUILD_DESKTOP=${{ env.BUILD_DESKTOP }} \
          BUILD_MINIMAL=${{ env.BUILD_MINIMAL }} \
          KERNEL_CONFIGURE=${{ env.KERNEL_CONFIGURE }} \
          SHOW_DEBUG=no \
          ${{ env.BUILD_ARGS }}
          
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: armbian-${{ env.BOARD }}-${{ env.RELEASE }}
        path: build/output/images/
        
    - name: 清理缓存 (可选)
      if: always()
      run: |
        sudo rm -rf build/cache
        sudo rm -rf build/output/debs
